### ISSUE TITLE
Wear notification icon is not changing 

### ISSUE THREAD

**Issue by soumyarout** [fnk0/Android-Wear-Codelab#1]
Hi,
This example is really nice, but I am wondering in simple notification the icon displayed in Watch is the launcher icon of handheld app. Even if I change the launcher icons or the small icon of notification in Android wear its still showing handheld device icons. :-(

Is there any way to change them?

Thanks,
Som

**Comment by fnk0** [comment]
Unfortunately not. If you take a look at all the apps notifications on wear you will notice that the icon displayed is always the App icon.
